version: '3'

services:
  app:
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://user:password@db/routes_db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: routes_db
    ports:
      - "5432:5432"
